import { City } from "../models/city.model";

export const ukraineMainCities: City[] = [
    { MapLabel: "map-label-1", Name: "Kyiv" },
    { MapLabel: "map-label-25", Name: "Zhytomyr" },
    { MapLabel: "map-label-22", Name: "Rivne" },
    { MapLabel: "map-label-14", Name: "Lutsk" },
    { MapLabel: "map-label-3", Name: "Lviv" },
    { MapLabel: "map-label-15", Name: "Uzhhorod" },
    { MapLabel: "map-label-11", Name: "Ivano-Frankivsk" },
    { MapLabel: "map-label-21", Name: "Chernivtsi" },
    { MapLabel: "map-label-17", Name: "Ternopil" },
    { MapLabel: "map-label-23", Name: "Khmelnytskyi" },
    { MapLabel: "map-label-10", Name: "Vinnytsia" },
    { MapLabel: "map-label-19", Name: "Cherkasy" },
    { MapLabel: "map-label-16", Name: "Kirovohrad" },
    { MapLabel: "map-label-13", Name: "Mykolayiv" },
    { MapLabel: "map-label-6", Name: "Odessa" },
    { MapLabel: "map-label-5", Name: "Kherson" },
    { MapLabel: "map-label-2", Name: "Sevastopol" },
    { MapLabel: "map-label-4", Name: "Zaporizhzhia" },
    { MapLabel: "map-label-9", Name: "Dnipropetrovsk" },
    { MapLabel: "map-label-7", Name: "Donetsk" },
    { MapLabel: "map-label-8", Name: "Luhansk" },
    { MapLabel: "map-label-18", Name: "Kharkiv" },
    { MapLabel: "map-label-12", Name: "Poltava" },
    { MapLabel: "map-label-24", Name: "Sumy" },
    { MapLabel: "map-label-20", Name: "Chernihiv" }
];